"""Render Balsa's root exports from Mojo 1.0 `mojo doc` JSON.

The compiler owns signatures and docstrings. Imports in __init__.mojo own the
public surface; internal codec/wire helpers are deliberately excluded.
"""

import argparse
import ast
import json
from pathlib import Path
import re
import subprocess
import tomllib

ROOT = Path(__file__).resolve().parents[1]


def declarations(module):
    return {
        item["name"]: item
        for kind in ("aliases", "structs", "functions", "traits")
        for item in module.get(kind, [])
    }


def public_api(package):
    modules = {m["name"]: m for m in package["modules"]}
    source = (ROOT / "src/balsa/__init__.mojo").read_text()
    result = []
    # Parse only Python-compatible import statements, not Mojo declarations.
    for match in re.finditer(r"^from \.\w+ import (?:\([^)]*\)|[^\n]+)", source, re.M):
        statement = ast.parse(match[0]).body[0]
        available = declarations(modules[statement.module])
        for name in statement.names:
            result.append((name.asname or name.name, statement.module, available[name.name]))
    result.extend((name, "__init__", item) for name, item in declarations(modules["__init__"]).items())
    return result


def prose(item):
    return "\n\n".join(item[key] for key in ("summary", "description") if item.get(key))


def signature(item):
    text = item["signature"]
    if item.get("raises") and " raises" not in text:
        before, arrow, after = text.rpartition(" -> ")
        text = before + " raises" + arrow + after if arrow else text + " raises"
    if item["kind"] == "alias":
        text += " = " + item["value"]
    return text


def render_decl(item, level):
    parts = ["```mojo\n" + signature(item) + "\n```"]
    if prose(item):
        parts.append(prose(item))
    if item.get("deprecated"):
        parts.append("Deprecated: " + item["deprecated"])
    for key, title in (("parameters", "Parameters"), ("args", "Arguments")):
        entries = [f"- `{a['name']}`: {a['description']}" for a in item.get(key, []) if a.get("description")]
        if entries:
            parts.append(title + ":\n\n" + "\n".join(entries))
    if item.get("returns", {}).get("description"):
        parts.append("Returns: " + item["returns"]["description"])
    if item.get("raisesDoc"):
        parts.append("Raises: " + item["raisesDoc"])
    if item.get("parentTraits"):
        parts.append("Traits: " + ", ".join("`" + t["name"] + "`" for t in item["parentTraits"]) + ".")
    if item.get("fields"):
        rows = ["| Field | Type | Description |", "| --- | --- | --- |"]
        for field in item["fields"]:
            cells = ["`" + field["name"] + "`", "`" + field["type"] + "`", prose(field)]
            rows.append("| " + " | ".join(c.replace("|", "\\|").replace("\n", " ") for c in cells) + " |")
        parts.append("\n".join(rows))
    for alias in item.get("aliases", []):
        parts.append("#" * level + " `" + alias["name"] + "`")
        parts.extend(render_decl(alias, level + 1))
    for function in item.get("functions", []):
        parts.append("#" * level + " `" + function["name"] + "`")
        for overload in function["overloads"]:
            parts.extend(render_decl(overload, level + 1))
    return parts


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in reference is stale")
    args = parser.parse_args()
    output = ROOT / "build/balsa-api.json"
    output.parent.mkdir(exist_ok=True)
    subprocess.run(["mojo", "doc", "--Werror", "-I", "src", "src/balsa", "-o", str(output)], cwd=ROOT, check=True)
    exports = public_api(json.loads(output.read_text())["decl"])
    version = next(item["value"] for name, _, item in exports if name == "__version__")
    manifest = tomllib.loads((ROOT / "pixi.toml").read_text())
    if json.loads(version) != manifest["workspace"]["version"]:
        raise SystemExit("balsa.__version__ and pixi.toml workspace.version disagree")
    parts = [
        "# Balsa API reference",
        "<!-- Generated by tools/api_docs.py from mojo doc; edit source docstrings. -->",
        'Regenerate with `pixi run -e docs docs`; verify with `pixi run -e docs docs-check`.\n'
        'The raw compiler reference is written to `build/balsa-api.json`.\n'
        'Compiler signatures may expand default values and normalize type names.',
        'All entries below are available from `balsa`. This is the supported public\n'
        'surface; other declarations in implementation modules are internal.\n'
        'See the [usage guide](usage.md) for examples and [API design](api-design.md)\n'
        'for import, ownership and version conventions.',
        "## Index\n\n" + "\n".join(f"- [`{name}`](#{name.lower()})" for name, _, _ in exports),
    ]
    for name, module, item in exports:
        parts.extend([f"## `{name}`", f"Defined in `balsa{'.' + module if module != '__init__' else ''}`."])
        for overload in item.get("overloads", [item]):
            parts.extend(render_decl(overload, 3))
    content = "\n\n".join(parts) + "\n"
    target = ROOT / "docs/api.md"
    if args.check:
        if not target.exists() or target.read_text() != content:
            raise SystemExit("API reference is stale; run pixi run -e docs docs")
        print("API reference is current; all root exports resolved.")
    else:
        target.write_text(content)
        print(f"Wrote {target.relative_to(ROOT)} ({len(exports)} public exports).")


if __name__ == "__main__":
    main()
